theme = "solarized_dark_transparent"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
X = "select_line_above"
ret = "goto_word"
C-q = ":q!"
C-s = ":wa"
C-r = ":rla"
C-y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
space.q = ":bc!"

[keys.select]
X = "select_line_above"

[editor.lsp]
display-messages = true
